# Stage 1: Build the application
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# Copy the pom.xml to fetch all dependencies
COPY pom.xml .

# Copy the project source
COPY src ./src

# Package the application
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:21-jdk-slim
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/target/pdftextextractor-1.0-SNAPSHOT.jar ./app.jar

# Run the Spring Boot application
CMD ["java", "-jar", "app.jar"]
